name: MALSAMI-FE-INTEGRATION-CICD

on:
  push:
    branches:
      - main
      - test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Log - Installing dependencies
        run: echo "의존성을 설치 중입니다..."

      - name: Install dependencies
        run: npm install

      - name: Log - Building project
        run: echo "프로젝트를 빌드 중입니다..."

      - name: Build with npm
        run: npm run build

      - name: Docker setup
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log - Setting up Docker cache
        run: echo "Docker 레이어 캐시를 설정 중입니다..."

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log - Building and pushing Docker image
        run: echo "Docker 이미지를 빌드하고 푸시 중입니다..."

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sejong-malsami-front-container:${{ github.ref_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 2022
          script: |
            echo "배포를 시작합니다..."
            export PATH=$PATH:/usr/local/bin
            export PW=${{ secrets.SERVER_PASSWORD }}
            BRANCH=${{ github.ref_name }}
            PORT=3000
            CONTAINER_NAME="sejong-malsami-front"
            
            if [ "$BRANCH" == "main" ]; then
              PORT=3004
              echo "메인 브랜치로 배포합니다. 포트는 $PORT입니다."
            elif [ "$BRANCH" == "test" ]; then
              CONTAINER_NAME="sejong-malsami-front-test"
              PORT=3003
              echo "테스트 브랜치로 배포합니다. 컨테이너 이름은 $CONTAINER_NAME, 포트는 $PORT입니다."
            fi
            
            echo "도커 이미지를 풀링 중입니다: ${{ secrets.DOCKERHUB_USERNAME }}/sejong-malsami-front-container:${BRANCH}"
            echo $PW | sudo -S docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sejong-malsami-front-container:${BRANCH}
            
            echo "기존 컨테이너를 중지합니다: $CONTAINER_NAME"
            echo $PW | sudo -S docker stop $CONTAINER_NAME || true
            
            echo "기존 컨테이너를 제거합니다: $CONTAINER_NAME"
            echo $PW | sudo -S docker rm $CONTAINER_NAME || true
            
            echo "새로운 컨테이너를 실행합니다: $CONTAINER_NAME on port $PORT"
            echo $PW | sudo -S docker run -d -p ${PORT}:3000 --name $CONTAINER_NAME \
              ${{ secrets.DOCKERHUB_USERNAME }}/sejong-malsami-front-container:${BRANCH}
            
            echo "배포가 완료되었습니다."
            
