name: MALSAMI-FE-EPIC-PR-CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches:
      - epic/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.0'

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-v20
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "의존성을 설치 중입니다..."
          npm ci

      - name: Run Tests
        run: |
          echo "테스트를 실행하고 있습니다..."
          npm test

      - name: Build Project
        run: |
          echo "프로젝트를 빌드 중입니다..."
          npm run build
